"""constraint unique index for content

Revision ID: ad2dd68987de
Revises: 7f62e781ce54
Create Date: 2025-05-17 16:44:59.649702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2dd68987de'
down_revision: Union[str, None] = '7f62e781ce54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_content_user_id_step_number', 'content', ['user_id', 'step_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_user_id_step_number', table_name='content')
    # ### end Alembic commands ###
